name: Build and upload Plugin
on:
  push:
    branches:
      - main
      - develop
    tags:
      - "v*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Generate version string
        id: version
        run: |
          if ${{ startsWith(github.ref_name, 'v') }}; then
            # use v1.2.3 tag
            echo "{plugin_version}=${{ github.ref_name  }}" >> $GITHUB_ENV
          else
            # use nightly-20231231-0000abcd
            echo "{plugin_version}=nightly-{$(date +'%Y-%m-%d')}-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          fi

      - name: Build plugin with HISE
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: false
          tags: plugin-build
          build-args: |
            "PLUGIN_VERSION=${{ env.plugin_version }}"

      - name: Copy artifacts from Docker image to /output/
        run: docker run -v /output:/mnt --rm plugin-build bash -c "cp -a /output/* /mnt/"

      - name: Upload artifacts for untagged builds
        uses: actions/upload-artifact@v3
        if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        with:
            name: plugin
            path: /output/

      - name: Release tagged builds
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: |
            /output/*
