name: Create and publish a Docker image
on:
  push:
    branches:
      - main
      - 'releases/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Build Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: false
          tags: plugin-build

      - name: Copy artifacts from Docker image to /output/
        run: docker run -v /output:/mnt -it --rm plugin-build bash -c "cp -a /output /mnt/"

      - name: Upload artifacts from /output/
        uses: actions/upload-artifact@v3
        with:
            name: plugin
            path: /output/
