name: Build and upload Plugin
on:
  push:
    branches:
      - main
      - develop
    tags:
      - "v*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Build Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: false
          tags: plugin-build

      - name: Copy artifacts from Docker image to /output/
        run: docker run -v /output:/mnt --rm plugin-build bash -c "cp -a /output/* /mnt/"

      - name: Upload artifacts from /output/
        uses: actions/upload-artifact@v3
        with:
            name: plugin
            path: /output/

      - name: Release tagged builds
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: |
            /output/*
